//! Provider/model/auth metadata vendored from oh-my-pi's `pi-catalog`.
//!
//! `data/omp-catalog.json` is generated by `scripts/sync-catalog.mjs` from the
//! pinned `@oh-my-pi/pi-catalog` release (see `scripts/OMP_VERSION`). It
//! carries upstream's compiled auth rules (login flows), api-routes table, and
//! model catalog, so clients reuse the ecosystem data instead of maintaining
//! provider tables by hand.
//!
//! Only the wire dialects this crate speaks are routable; providers whose
//! models all resolve to unsupported APIs stay visible for BYOK config but
//! cannot be logged in or picked.

use crate::Protocol;
use serde_json::Value;
use std::collections::BTreeMap;
use std::sync::OnceLock;

const CATALOG_JSON: &str = include_str!("../data/omp-catalog.json");

/// Parsed view over the vendored artifact. Deserialization is manual
/// (`serde_json::Value`, matching crate convention) and happens once.
pub struct OmpCatalog {
    /// The `@oh-my-pi/pi-catalog` release this data was generated from.
    pub omp_version: String,
    providers: Vec<AuthProvider>,
    api_routes: Vec<ProviderRoutes>,
    default_models: BTreeMap<String, String>,
    models: BTreeMap<String, Vec<CatalogModel>>,
}

/// One `auth "<id>"` rule compiled by upstream — how a provider is
/// authenticated (env vars, api-key, OAuth) and whether credentials renew.
pub struct AuthProvider {
    pub id: String,
    pub name: String,
    /// "bearer" or "structured" (JSON-encoded credential metadata).
    pub api_key_format: String,
    pub login: Option<LoginRule>,
    pub refresh: Option<RefreshRule>,
    /// Plain env-var names that can supply the credential (`env vars`).
    pub env_vars: Vec<String>,
    /// Named env hook upstream resolves in TypeScript; we can't run it.
    pub env_hook: Option<String>,
    pub allows_missing_api_key: bool,
    /// Credential/model slot this provider shares (e.g. `openai-codex-device`
    /// stores as `openai-codex`, `zai-coding-plan` as `zai`).
    pub store_as: Option<String>,
    /// Login accepts a pasted redirect/code when the local listener can't run.
    pub paste_code: bool,
    /// `result "api-key"`: the OAuth outcome is stored as a raw API key.
    pub result_is_api_key: bool,
}

/// A KDL value node: literal (possibly base64-wrapped), env override, or a
/// TypeScript hook we cannot evaluate — callers must handle `hook` errors.
pub struct AuthValue {
    pub value: Option<String>,
    pub env: Vec<String>,
    pub base64: bool,
    pub hook: Option<String>,
}

/// Login flow declared by an auth rule.
pub enum LoginRule {
    ApiKey(Box<ApiKeyLogin>),
    OauthCode(Box<OauthCodeLogin>),
    DeviceCode(Box<DeviceCodeLogin>),
    /// Whole-flow hook (`github-copilot`, `cursor`, …). Not portable — the
    /// provider is reported unsupported for login.
    Custom {
        hook: String,
    },
}

pub struct ApiKeyLogin {
    pub auth_url: Option<String>,
    pub instructions: Option<String>,
    pub prompt: Option<String>,
    pub placeholder: Option<String>,
    /// e.g. "strip-bearer" — normalize pasted input before storing.
    pub normalize: Option<String>,
    pub validate: Option<ApiKeyValidate>,
}

/// Declared key-validation probe. `models-endpoint` = GET with the key as
/// bearer; `chat-completions` = minimal chat request against `base_url`.
pub struct ApiKeyValidate {
    pub kind: String,
    pub label: Option<String>,
    pub url: Option<String>,
    pub base_url: Option<String>,
    pub model: Option<String>,
}

pub struct OauthCodeLogin {
    pub client_id: Option<AuthValue>,
    pub client_secret: Option<AuthValue>,
    pub authorize_url: AuthValue,
    pub scopes: Vec<String>,
    pub scope_separator: String,
    pub pkce: bool,
    /// "hex" | "uuid" | "none".
    pub state: String,
    pub standard_authorize_params: bool,
    pub authorize_params: Vec<(String, String)>,
    pub instructions: Option<String>,
    pub callback: CallbackRule,
    pub token: TokenRequest,
    pub credential: CredentialMap,
    pub userinfo: Option<UserinfoRule>,
    /// after-exchange hook name (identity enrichment we can't run).
    pub after_exchange: Option<String>,
}

pub struct CallbackRule {
    pub port: u16,
    pub path: String,
    pub hostname: String,
    /// Try an ephemeral port when the preferred one is taken.
    pub port_fallback: bool,
    /// No local listener — the user must paste the redirect manually.
    pub manual_only: bool,
    /// Callback arrives on a custom URI scheme, not loopback HTTP.
    pub native_scheme: bool,
    pub redirect_uri: Option<AuthValue>,
}

pub struct DeviceCodeLogin {
    pub client_id: AuthValue,
    pub base_url: Option<AuthValue>,
    pub scopes: Vec<String>,
    pub scope_separator: String,
    /// headersHook name (e.g. kimi telemetry headers).
    pub headers_hook: Option<String>,
    pub device: TokenRequest,
    pub token: TokenRequest,
    pub response: DeviceResponseMap,
    pub instructions: String,
    pub credential: CredentialMap,
    pub userinfo: Option<UserinfoRule>,
    pub after_exchange: Option<String>,
}

/// JSON paths into the device-authorization response.
pub struct DeviceResponseMap {
    pub user_code: Option<String>,
    pub device_code: Option<String>,
    pub verification_uri: Option<String>,
    pub verification_uri_complete: Option<String>,
    pub interval: Option<String>,
    pub expires_in: Option<String>,
}

/// A declared token-style POST: URL, body encoding, baseline-param flag and
/// templated params/headers.
pub struct TokenRequest {
    pub url: AuthValue,
    /// "form" | "json".
    pub body: String,
    /// Include the grant's standard params (grant_type, code, …).
    pub standard: bool,
    pub params: Vec<(String, String)>,
    pub headers: Vec<(String, String)>,
    pub timeout_ms: Option<u64>,
}

/// Bearer GET that fills identity fields after a token exchange.
pub struct UserinfoRule {
    pub url: String,
    pub email: Option<String>,
    pub account_id: Option<String>,
}

/// A credential slot: dotted JSON path into the response, JWT claim names,
/// or a literal.
#[derive(Default)]
pub struct CredentialField {
    pub path: Option<String>,
    pub claims: Vec<String>,
    pub literal: Option<String>,
}

/// Token-response → stored-credential projection.
#[derive(Default)]
pub struct CredentialMap {
    pub access: CredentialField,
    pub refresh: Option<CredentialField>,
    pub expires: ExpiresRule,
    pub email: Option<CredentialField>,
    pub account_id: Option<CredentialField>,
    pub org_id: Option<CredentialField>,
    pub org_name: Option<CredentialField>,
    pub project_id: Option<CredentialField>,
    pub api_endpoint: Option<CredentialField>,
    pub enterprise_url: Option<CredentialField>,
}

#[derive(Default)]
pub enum ExpiresRule {
    #[default]
    Never,
    /// Read `exp` off the access-token JWT; fallback when not a JWT.
    Jwt {
        skew_ms: u64,
        fallback_ms: Option<u64>,
    },
    /// `seconds` value at `path`, optionally relative to `from_path` epoch.
    Seconds {
        path: String,
        from_path: Option<String>,
        skew_ms: u64,
        fallback_ms: Option<u64>,
    },
}

/// Refresh declaration: a token POST, a hook we can't run, or none (the
/// credential is long-lived and expiry means re-login).
pub struct RefreshRule {
    /// "request" | "hook" | "none".
    pub kind: String,
    pub token: Option<TokenRequest>,
    pub credential: Option<CredentialMap>,
    pub userinfo: Option<UserinfoRule>,
    pub hook: Option<String>,
    /// headersHook name (e.g. kimi telemetry headers).
    pub headers_hook: Option<String>,
    /// Credential fields that must be present to attempt refresh.
    pub require: Vec<String>,
}

/// One model entry from upstream's generated catalog.
pub struct CatalogModel {
    pub id: String,
    pub name: String,
    /// Wire dialect id ("anthropic-messages", "openai-completions", …).
    pub api: String,
    pub provider: String,
    pub base_url: String,
    pub context_window: u64,
    pub max_tokens: u64,
    pub reasoning: bool,
    pub input: Vec<String>,
    /// USD per 1M tokens; 0 = unknown (upstream publishes numbers).
    pub input_cost: f64,
    pub cached_input_cost: f64,
    pub output_cost: f64,
}

struct ProviderRoutes {
    provider: String,
    routes: Vec<ApiRoute>,
    default: Option<String>,
}

struct ApiRoute {
    api: String,
    exact: Vec<String>,
    prefix: Vec<String>,
    glob: Vec<String>,
    strip_prefix: bool,
}

/// Result of resolving (provider, model id) through the api-routes table.
pub struct ResolvedRoute<'a> {
    pub api: &'a str,
    /// Model id to send upstream — prefix stripped when the route says so.
    pub wire_model: String,
}

static CATALOG: OnceLock<OmpCatalog> = OnceLock::new();

/// The vendored catalog, parsed on first use.
pub fn catalog() -> &'static OmpCatalog {
    CATALOG.get_or_init(|| {
        let value: Value =
            serde_json::from_str(CATALOG_JSON).expect("vendored omp-catalog.json is valid JSON");
        OmpCatalog::parse(&value)
    })
}

/// Maps an upstream wire-dialect id to a protocol this crate implements.
/// `google-*`/`bedrock-*` and agent-specific dialects (`cursor-agent`,
/// `devin-agent`, …) need request shaping we don't have — deliberately
/// unmapped.
pub fn protocol_for_api(api: &str) -> Option<Protocol> {
    match api {
        "anthropic-messages" => Some(Protocol::AnthropicMessages),
        "openai-completions" | "openrouter" => Some(Protocol::OpenAiChatCompletions),
        "openai-responses" => Some(Protocol::OpenAiResponses),
        "openai-codex-responses" => Some(Protocol::OpenAiCodexResponses),
        "azure-openai-responses" => Some(Protocol::AzureOpenAiResponses),
        _ => None,
    }
}

impl OmpCatalog {
    fn parse(root: &Value) -> Self {
        let providers = root
            .get("authProviders")
            .and_then(Value::as_array)
            .map(|items| items.iter().filter_map(parse_auth_provider).collect())
            .unwrap_or_default();
        let api_routes = root
            .get("apiRoutes")
            .and_then(Value::as_array)
            .map(|items| items.iter().filter_map(parse_provider_routes).collect())
            .unwrap_or_default();
        let mut models: BTreeMap<String, Vec<CatalogModel>> = BTreeMap::new();
        if let Some(table) = root.get("models").and_then(Value::as_object) {
            for (provider, entries) in table {
                let mut list: Vec<CatalogModel> = entries
                    .as_object()
                    .map(|map| map.values().filter_map(parse_catalog_model).collect())
                    .unwrap_or_default();
                list.sort_by(|a, b| a.id.cmp(&b.id));
                models.insert(provider.clone(), list);
            }
        }
        let default_models = root
            .get("defaultModels")
            .and_then(Value::as_object)
            .map(|map| {
                map.iter()
                    .filter_map(|(k, v)| v.as_str().map(|s| (k.clone(), s.to_string())))
                    .collect()
            })
            .unwrap_or_default();
        Self {
            omp_version: str_field(root, "ompVersion").unwrap_or_default(),
            providers,
            api_routes,
            default_models,
            models,
        }
    }

    /// Auth rule for a provider id.
    pub fn auth_provider(&self, id: &str) -> Option<&AuthProvider> {
        self.providers.iter().find(|p| p.id == id)
    }

    /// All auth rules, in upstream `/login` display order.
    pub fn auth_providers(&self) -> &[AuthProvider] {
        &self.providers
    }

    /// Catalog models for a provider — following `store_as` so aliased
    /// providers (e.g. `zai-coding-plan` → `zai`) see the shared table.
    pub fn models(&self, provider: &str) -> &[CatalogModel] {
        if let Some(list) = self.models.get(provider) {
            if !list.is_empty() {
                return list;
            }
        }
        let alias = self
            .auth_provider(provider)
            .and_then(|p| p.store_as.as_deref())
            .unwrap_or(provider);
        self.models.get(alias).map(Vec::as_slice).unwrap_or(&[])
    }

    /// Models whose dialect this crate can actually serve.
    pub fn supported_models<'a>(
        &'a self,
        provider: &str,
        list: &'a [CatalogModel],
    ) -> Vec<&'a CatalogModel> {
        list.iter()
            .filter(|m| self.protocol_for(provider, &m.id).is_some())
            .collect()
    }

    /// The provider's default base URL: the first supported model's baseUrl.
    /// Per-model URLs (gitlab-duo's split proxies) resolve via `base_url_for`.
    pub fn default_base_url(&self, provider: &str) -> Option<&str> {
        let models = self.models(provider);
        self.supported_models(provider, models)
            .first()
            .map(|m| m.base_url.as_str())
            .filter(|url| !url.is_empty())
    }

    /// Base URL for a specific model; falls back to the provider default.
    pub fn base_url_for(&self, provider: &str, model: &str) -> Option<&str> {
        self.models(provider)
            .iter()
            .find(|m| m.id == model)
            .map(|m| m.base_url.as_str())
            .filter(|url| !url.is_empty())
            .or_else(|| self.default_base_url(provider))
    }

    /// Wire dialect for (provider, model): api-routes rules win over the
    /// model's declared `api`, matching upstream's routing order.
    pub fn api_for(&self, provider: &str, model: &str) -> Option<&str> {
        self.resolve(provider, model).map(|r| r.api)
    }

    /// Route (provider, model) to a dialect via the provider's api-routes
    /// table, else the model's own `api` field.
    pub fn resolve<'a>(&'a self, provider: &str, model: &str) -> Option<ResolvedRoute<'a>> {
        for entry in &self.api_routes {
            if entry.provider != provider {
                continue;
            }
            for route in &entry.routes {
                let matched = route.exact.iter().any(|e| e == model)
                    || route.prefix.iter().any(|p| model.starts_with(p.as_str()))
                    || route.glob.iter().any(|g| glob_match(g, model));
                if matched {
                    let wire_model = if route.strip_prefix {
                        route
                            .prefix
                            .iter()
                            .find(|p| model.starts_with(p.as_str()))
                            .map(|p| model[p.len()..].to_string())
                            .unwrap_or_else(|| model.to_string())
                    } else {
                        model.to_string()
                    };
                    return Some(ResolvedRoute {
                        api: &route.api,
                        wire_model,
                    });
                }
            }
            if let Some(default) = &entry.default {
                return Some(ResolvedRoute {
                    api: default,
                    wire_model: model.to_string(),
                });
            }
            // Provider has a routes table but no default and no match:
            // fall through to the model's declared api.
            break;
        }
        self.models(provider)
            .iter()
            .find(|m| m.id == model)
            .map(|m| ResolvedRoute {
                api: m.api.as_str(),
                wire_model: model.to_string(),
            })
    }

    /// Protocol for (provider, model), if the dialect is supported.
    pub fn protocol_for(&self, provider: &str, model: &str) -> Option<Protocol> {
        self.api_for(provider, model).and_then(protocol_for_api)
    }

    /// Upstream's curated default model for a provider.
    pub fn default_model(&self, provider: &str) -> Option<&str> {
        self.default_models
            .get(provider)
            .or_else(|| {
                self.auth_provider(provider)
                    .and_then(|p| p.store_as.as_ref())
                    .and_then(|alias| self.default_models.get(alias))
            })
            .map(String::as_str)
    }

    /// Can a client use this provider at all — at least one model on a
    /// supported dialect, or a key-only provider users fill in manually.
    pub fn provider_usable(&self, provider: &str) -> bool {
        let models = self.models(provider);
        models.is_empty() || !self.supported_models(provider, models).is_empty()
    }
}

/// Glob match supporting `*` and `?` (upstream api-routes glob semantics).
fn glob_match(pattern: &str, text: &str) -> bool {
    let pat: Vec<char> = pattern.chars().collect();
    let txt: Vec<char> = text.chars().collect();
    let (mut p, mut t) = (0, 0);
    let (mut star, mut star_t) = (usize::MAX, 0);
    while t < txt.len() {
        if p < pat.len() && (pat[p] == '?' || pat[p] == txt[t]) {
            p += 1;
            t += 1;
        } else if p < pat.len() && pat[p] == '*' {
            star = p;
            star_t = t;
            p += 1;
        } else if star != usize::MAX {
            p = star + 1;
            star_t += 1;
            t = star_t;
        } else {
            return false;
        }
    }
    while p < pat.len() && pat[p] == '*' {
        p += 1;
    }
    p == pat.len()
}

// ---- parsing helpers ------------------------------------------------------

fn str_field(v: &Value, key: &str) -> Option<String> {
    v.get(key).and_then(Value::as_str).map(str::to_string)
}

fn bool_field(v: &Value, key: &str) -> bool {
    v.get(key).and_then(Value::as_bool).unwrap_or(false)
}

fn u64_field(v: &Value, key: &str) -> Option<u64> {
    v.get(key).and_then(Value::as_u64)
}

fn f64_field(v: &Value, key: &str) -> f64 {
    v.get(key).and_then(Value::as_f64).unwrap_or(0.0)
}

fn str_vec(v: &Value, key: &str) -> Vec<String> {
    v.get(key)
        .and_then(Value::as_array)
        .map(|items| {
            items
                .iter()
                .filter_map(Value::as_str)
                .map(str::to_string)
                .collect()
        })
        .unwrap_or_default()
}

/// Ordered string map (KDL param order is preserved in the compiled JSON).
fn str_pairs(v: &Value, key: &str) -> Vec<(String, String)> {
    v.get(key)
        .and_then(Value::as_object)
        .map(|map| {
            map.iter()
                .filter_map(|(k, val)| val.as_str().map(|s| (k.clone(), s.to_string())))
                .collect()
        })
        .unwrap_or_default()
}

fn parse_auth_value(v: Option<&Value>) -> Option<AuthValue> {
    let v = v?;
    Some(AuthValue {
        value: str_field(v, "value"),
        env: str_vec(v, "env"),
        base64: v.get("encoding").and_then(Value::as_str) == Some("base64"),
        hook: str_field(v, "hook"),
    })
}

fn parse_credential_field(v: Option<&Value>) -> CredentialField {
    v.map(|v| CredentialField {
        path: str_field(v, "path"),
        claims: str_vec(v, "claim"),
        literal: str_field(v, "literal"),
    })
    .unwrap_or_default()
}

fn parse_expires(v: &Value) -> ExpiresRule {
    let get = |key: &str| v.get(key).and_then(Value::as_u64);
    match v.get("mode").and_then(Value::as_str) {
        Some("jwt") => ExpiresRule::Jwt {
            skew_ms: get("skewMs").unwrap_or(0),
            fallback_ms: get("fallbackMs"),
        },
        Some("seconds") => ExpiresRule::Seconds {
            path: str_field(v, "path").unwrap_or_else(|| "expires_in".to_string()),
            from_path: str_field(v, "fromPath"),
            skew_ms: get("skewMs").unwrap_or(0),
            fallback_ms: get("fallbackMs"),
        },
        _ => ExpiresRule::Never,
    }
}

fn parse_credential_map(v: Option<&Value>) -> CredentialMap {
    let empty = CredentialField::default();
    let field = |key: &str| {
        v.and_then(|m| m.get(key))
            .map(|f| parse_credential_field(Some(f)))
    };
    CredentialMap {
        access: v
            .and_then(|m| m.get("access"))
            .map(|f| parse_credential_field(Some(f)))
            .unwrap_or(empty),
        refresh: field("refresh"),
        expires: v
            .and_then(|m| m.get("expires"))
            .map(parse_expires)
            .unwrap_or(ExpiresRule::Never),
        email: field("email"),
        account_id: field("accountId"),
        org_id: field("orgId"),
        org_name: field("orgName"),
        project_id: field("projectId"),
        api_endpoint: field("apiEndpoint"),
        enterprise_url: field("enterpriseUrl"),
    }
}

fn parse_token_request(v: Option<&Value>) -> Option<TokenRequest> {
    let v = v?;
    Some(TokenRequest {
        url: parse_auth_value(v.get("url"))?,
        body: str_field(v, "body").unwrap_or_else(|| "form".to_string()),
        standard: v.get("standard").and_then(Value::as_bool).unwrap_or(true),
        params: str_pairs(v, "params"),
        headers: str_pairs(v, "headers"),
        timeout_ms: u64_field(v, "timeoutMs"),
    })
}

fn parse_userinfo(v: Option<&Value>) -> Option<UserinfoRule> {
    let v = v?;
    Some(UserinfoRule {
        url: str_field(v, "url")?,
        email: str_field(v, "email"),
        account_id: str_field(v, "accountId"),
    })
}

fn parse_refresh(v: Option<&Value>) -> Option<RefreshRule> {
    let v = v?;
    Some(RefreshRule {
        kind: str_field(v, "kind").unwrap_or_else(|| "none".to_string()),
        token: parse_token_request(v.get("token")),
        credential: v.get("credential").map(|c| parse_credential_map(Some(c))),
        userinfo: parse_userinfo(v.get("userinfo")),
        hook: str_field(v, "hook"),
        headers_hook: str_field(v, "headersHook"),
        require: str_vec(v, "require"),
    })
}

fn parse_login(v: Option<&Value>) -> Option<LoginRule> {
    let v = v?;
    match v.get("kind").and_then(Value::as_str)? {
        "api-key" => Some(LoginRule::ApiKey(Box::new(ApiKeyLogin {
            auth_url: str_field(v, "authUrl"),
            instructions: str_field(v, "instructions"),
            prompt: str_field(v, "prompt"),
            placeholder: str_field(v, "placeholder"),
            normalize: str_field(v, "normalize"),
            validate: v.get("validate").map(|val| ApiKeyValidate {
                kind: str_field(val, "kind").unwrap_or_default(),
                label: str_field(val, "label"),
                url: str_field(val, "url"),
                base_url: str_field(val, "baseUrl"),
                model: str_field(val, "model"),
            }),
        }))),
        "oauth-code" => Some(LoginRule::OauthCode(Box::new(OauthCodeLogin {
            client_id: parse_auth_value(v.get("clientId")),
            client_secret: parse_auth_value(v.get("clientSecret")),
            authorize_url: parse_auth_value(v.get("authorizeUrl"))?,
            scopes: str_vec(v, "scopes"),
            scope_separator: str_field(v, "scopeSeparator").unwrap_or_else(|| " ".to_string()),
            pkce: bool_field(v, "pkce"),
            state: str_field(v, "state").unwrap_or_else(|| "none".to_string()),
            standard_authorize_params: v
                .get("standardAuthorizeParams")
                .and_then(Value::as_bool)
                .unwrap_or(true),
            authorize_params: str_pairs(v, "authorizeParams"),
            instructions: str_field(v, "instructions"),
            callback: parse_callback(v.get("callback"))?,
            token: parse_token_request(v.get("token"))?,
            credential: parse_credential_map(v.get("credential")),
            userinfo: parse_userinfo(v.get("userinfo")),
            after_exchange: str_field(v, "afterExchange"),
        }))),
        "device-code" => Some(LoginRule::DeviceCode(Box::new(DeviceCodeLogin {
            client_id: parse_auth_value(v.get("clientId"))?,
            base_url: parse_auth_value(v.get("baseUrl")),
            scopes: str_vec(v, "scopes"),
            scope_separator: str_field(v, "scopeSeparator").unwrap_or_else(|| " ".to_string()),
            headers_hook: str_field(v, "headersHook"),
            device: parse_token_request(v.get("device"))?,
            token: parse_token_request(v.get("token"))?,
            response: parse_device_response(v.get("response")),
            instructions: str_field(v, "instructions").unwrap_or_default(),
            credential: parse_credential_map(v.get("credential")),
            userinfo: parse_userinfo(v.get("userinfo")),
            after_exchange: str_field(v, "afterExchange"),
        }))),
        "custom" => Some(LoginRule::Custom {
            hook: str_field(v, "hook").unwrap_or_default(),
        }),
        _ => None,
    }
}

fn parse_callback(v: Option<&Value>) -> Option<CallbackRule> {
    let v = v?;
    Some(CallbackRule {
        port: u64_field(v, "port").unwrap_or(0) as u16,
        path: str_field(v, "path").unwrap_or_else(|| "/callback".to_string()),
        hostname: str_field(v, "hostname").unwrap_or_else(|| "localhost".to_string()),
        port_fallback: bool_field(v, "portFallback"),
        manual_only: bool_field(v, "manualOnly"),
        native_scheme: bool_field(v, "nativeScheme"),
        redirect_uri: parse_auth_value(v.get("redirectUri")),
    })
}

fn parse_device_response(v: Option<&Value>) -> DeviceResponseMap {
    let get = |key: &str| {
        v.and_then(|r| r.get(key))
            .and_then(Value::as_str)
            .map(str::to_string)
    };
    DeviceResponseMap {
        user_code: get("userCode"),
        device_code: get("deviceCode"),
        verification_uri: get("verificationUri"),
        verification_uri_complete: get("verificationUriComplete"),
        interval: get("interval"),
        expires_in: get("expiresIn"),
    }
}

fn parse_auth_provider(v: &Value) -> Option<AuthProvider> {
    let env = v.get("env");
    Some(AuthProvider {
        id: str_field(v, "id")?,
        name: str_field(v, "name").unwrap_or_default(),
        api_key_format: str_field(v, "apiKeyFormat").unwrap_or_else(|| "bearer".to_string()),
        login: parse_login(v.get("login")),
        refresh: parse_refresh(v.get("refresh")),
        env_vars: env.map(|e| str_vec(e, "vars")).unwrap_or_default(),
        env_hook: env.and_then(|e| str_field(e, "hook")),
        allows_missing_api_key: bool_field(v, "allowsMissingApiKey"),
        store_as: str_field(v, "storeAs"),
        paste_code: bool_field(v, "pasteCode"),
        result_is_api_key: v.get("result").and_then(Value::as_str) == Some("api-key"),
    })
}

fn parse_provider_routes(v: &Value) -> Option<ProviderRoutes> {
    let routes = v
        .get("routes")
        .and_then(Value::as_array)
        .map(|items| {
            items
                .iter()
                .filter_map(|r| {
                    let m = r.get("match")?;
                    Some(ApiRoute {
                        api: str_field(r, "api")?,
                        exact: str_vec(m, "exact"),
                        prefix: str_vec(m, "prefix"),
                        glob: str_vec(m, "glob"),
                        strip_prefix: r
                            .get("stripPrefix")
                            .and_then(Value::as_bool)
                            .unwrap_or(false),
                    })
                })
                .collect()
        })
        .unwrap_or_default();
    Some(ProviderRoutes {
        provider: str_field(v, "provider")?,
        routes,
        default: str_field(v, "default"),
    })
}

fn parse_catalog_model(v: &Value) -> Option<CatalogModel> {
    let cost = v.get("cost");
    Some(CatalogModel {
        id: str_field(v, "id")?,
        name: str_field(v, "name").unwrap_or_default(),
        api: str_field(v, "api").unwrap_or_default(),
        provider: str_field(v, "provider").unwrap_or_default(),
        base_url: str_field(v, "baseUrl").unwrap_or_default(),
        context_window: u64_field(v, "contextWindow").unwrap_or(0),
        max_tokens: u64_field(v, "maxTokens").unwrap_or(0),
        reasoning: bool_field(v, "reasoning"),
        input: str_vec(v, "input"),
        input_cost: cost.map(|c| f64_field(c, "input")).unwrap_or(0.0),
        cached_input_cost: cost.map(|c| f64_field(c, "cacheRead")).unwrap_or(0.0),
        output_cost: cost.map(|c| f64_field(c, "output")).unwrap_or(0.0),
    })
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn catalog_parses_pinned_data() {
        let catalog = catalog();
        assert!(!catalog.omp_version.is_empty());
        assert!(catalog.auth_provider("anthropic").is_some());
        assert!(catalog.auth_provider("openrouter").is_some());
    }

    #[test]
    fn protocol_maps_only_supported_dialects() {
        assert_eq!(
            protocol_for_api("anthropic-messages"),
            Some(Protocol::AnthropicMessages)
        );
        assert_eq!(
            protocol_for_api("openai-completions"),
            Some(Protocol::OpenAiChatCompletions)
        );
        assert_eq!(
            protocol_for_api("openai-responses"),
            Some(Protocol::OpenAiResponses)
        );
        assert_eq!(
            protocol_for_api("openai-codex-responses"),
            Some(Protocol::OpenAiCodexResponses)
        );
        assert_eq!(
            protocol_for_api("azure-openai-responses"),
            Some(Protocol::AzureOpenAiResponses)
        );
        assert_eq!(protocol_for_api("google-generative-ai"), None);
        assert_eq!(protocol_for_api("bedrock-converse-stream"), None);
    }

    #[test]
    fn resolves_model_api_from_catalog() {
        let catalog = catalog();
        assert_eq!(
            catalog.api_for("anthropic", "claude-sonnet-4-5"),
            Some("anthropic-messages")
        );
        assert_eq!(
            catalog.protocol_for("deepseek", "deepseek-v4-pro"),
            Some(Protocol::OpenAiChatCompletions)
        );
    }

    #[test]
    fn store_as_shares_the_target_model_table() {
        let catalog = catalog();
        // zai-coding-plan has no own table in models.json; it shares zai's.
        assert_eq!(
            catalog.models("zai-coding-plan").len(),
            catalog.models("zai").len()
        );
    }

    #[test]
    fn glob_matcher_handles_star_and_question() {
        assert!(glob_match("claude-*", "claude-opus-4-8"));
        assert!(glob_match("gpt-?", "gpt-6"));
        assert!(!glob_match("claude-*", "gpt-5"));
        assert!(glob_match("*", "anything"));
        assert!(glob_match("a*c", "abc"));
        assert!(!glob_match("a*c", "abd"));
    }

    #[test]
    fn oauth_code_login_parses_full_rule() {
        let catalog = catalog();
        let provider = catalog.auth_provider("anthropic").unwrap();
        let Some(LoginRule::OauthCode(login)) = &provider.login else {
            panic!("anthropic should be oauth-code");
        };
        assert!(login.pkce);
        assert!(login.client_id.is_some());
        assert_eq!(login.callback.port, 54545);
        assert!(login.callback.port_fallback);
    }
}
